[package]
name = "model"
version = "2.0.0"
publish = false
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = { version = "1.0" }
time = { version = "0.3", features = ["serde", "parsing"] }

