[db]
endpoint = "localhost"
port = 5101
username = "analytics_local"
password = "analytics_local"
dbname = "analytics_local"

[auth]
# This is a very poor key, but it shouldn't trigger GitHub
token_key = "YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE="
