[files]
extend-exclude = ["static/*"]

[default]
extend-ignore-identifiers-re = [
  "ure\\d+",
  "UE\\d+",
  "bse\\d+",
]

[default.extend-words]
grap = "grap"
Som = "Som"
ue306 = "UE306"
ure0 = "ure0"
Vesseles = "Vesseles"
