[package]
name = "site"
version = "2.0.0"
edition = "2021"
publish = false

[profile.release]
lto = true
opt-level = 'z'

[features]
hydration = [
  "yew/hydration"
]

static = [
  "yew/ssr"
]

[[bin]]
name = "site-build"
required-features = [
  "static",
]

[[bin]]
name = "site"

[dependencies]
async-trait = { version = "0.1" }
gray_matter = { version = "0.2", default-features = false, features = ["yaml"] }
include_dir = { version = "0.7" }
yew = { version = "0.20" }
yew-hooks = { version = "0.2" }
yew-router = { version = "0.17" }
log = { version = "0.4" }
pulldown-cmark = { version = "0.9" }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
serde_yaml = { version = "0.9" }
thiserror = { version = "1.0" }
words-count = { version = "0.1" }

[dependencies.time]
version = "0.3"
features = [
  "formatting",
  "local-offset",
  "macros",
  "parsing",
  "serde",
  "wasm-bindgen"
]
[dependencies.yew_icons]
version = "0.7"
features = [
  "BootstrapDot",
  "BootstrapGithub",
  "BootstrapMastodon",
  "LucideMenu",
  "LucideRss"
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { version = "0.4" }
wasm-logger = { version = "0.2" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.32", features = ["full"] }
env_logger = { version = "0.10" }

