[package]
name = "site"
version = "2.0.0"
edition = "2021"
publish = false

[features]
hydration = [
  "yew/hydration"
]

static = [
  "yew/ssr"
]

[[bin]]
name = "site-build"
required-features = [
  "static",
]

[[bin]]
name = "site"

[dependencies]
yew = { version = "0.20" }
yew-router = { version = "0.17" }
log = { version = "0.4" }
futures = { version = "0.3", features = ["std"], default-features = false }

[dependencies.yew_icons]
version = "0.7"
features = [
  "LucideRss"
]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = { version = "0.4" }
wasm-logger = { version = "0.2" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.32", features = ["full"] }
env_logger = { version = "0.10" }

