baseURL = 'https://blakerain.com/'
languageCode = 'en-GB'
title = 'Blake Rain'

[menus]
  [[menus.footer_right]]
    name = "Tags"
    pageRef = "/tags"
    weight = 10
  [[menus.footer_right]]
    name = "Tools"
    pageRef = "/tools"
    weight = 10
  [[menus.footer_right]]
    name = "RSS"
    url = "/blog/index.xml"
    weight = 10

[related]
  includeNewer = true
  threshold = 80
  [[related.indices]]
    name = "tags"
    type = "basic"
    weight = 80
    toLower = true

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    noClasses = false
    wrapperClass = "highlight"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"
  [[module.imports]]
    path = "github.com/hugomods/icons/vendors/devicons"
  [[module.imports]]
    path = "github.com/hugomods/icons/vendors/lucide"
  [[module.imports]]
    path = "github.com/hugomods/icons/vendors/bootstrap"
  [[module.imports]]
    path = "github.com/hugomods/icons/vendors/font-awesome"
  [[module.imports]]
    path = "github.com/hugomods/icons/vendors/simple-icons"
  [[module.imports]]
    path = "github.com/hugomods/encoder"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "main\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
