baseURL = 'https://blakerain.com/'
languageCode = 'en-GB'
title = 'Blake Rain'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.112.0"
  [[module.imports]]
    path = "github.com/hugomods/icons/vendors/lucide"
  [[module.imports]]
    path = "github.com/hugomods/icons/vendors/bootstrap"
  [[module.imports]]
    path = "github.com/hugomods/encoder"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"
  [[module.mounts]]
    source = "node_modules/hyperscript.org/dist/_hyperscript.min.js"
    target = "static/scripts/vendor/hyperscript.js"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "main\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"
