routes:
  /:
    controller: channel
    filter: tag:hash-blog

collections:
  /blog/:
    permalink: /blog/{slug}/
    filter: tag:hash-blog
    rss: true

  /projects/:
    permalink: /projects/{slug}/
    filter: tag:hash-project
    rss: false

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
