routes:
  /:
    data: page.root
    template: root

collections:
  /blog/:
    permalink: /blog/{slug}/
    filter: tag:hash-blog
    rss: true

  /projects/:
    permalink: /projects/{slug}/
    filter: tag:hash-project
    rss: false

  /tips/:
    permalink: /tips/{slug}/
    filter: tag:hash-tip
    rss: false

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
