name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: docker
    steps:
      - name: Install Dependencies
        run: |
          apt-get update -y
          apt-get install -y curl build-essential

      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 25

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11

      - name: Install Rust
        uses: https://git.blakerain.com/actions/setup-rust-toolchain@forgejo
        with:
          toolchain: stable
          components: clippy

      - name: Build the site
        run: make release

      - name: Check typos
        uses: https://github.com/crate-ci/typos@master
