name: deploy

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: docker
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install node dependencies
        run: |
          npm i

      - name: Setup node
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Setup hugo
        uses: https://github.com/peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build the site
        run: hugo --minify

      - name: Deploy the site
        run: |
          docker run --rm \
            -v blakerain_com:/dest \
            -v ${{ github.workspace }}/public:/src \
            alpine sh "rsync -chrlvzi --delete /src/ /dest/"

      # - name: Deploy the site
      #   run: |
      #     apt-get update -y
      #     apt-get install -y rsync
      #     echo "${{ secrets.SSH_DEPLOYMENT_KEY }}" > deploy_key
      #     chmod 600 ./deploy_key
      #     rsync -chrlvzi --delete \
      #       -e 'ssh -i ./deploy_key -p 22 -o StrictHostKeyChecking=no' \
      #       public/ \
      #       blakerain-com@blakerain.com:/
      #     rm ./deploy_key
