name: check

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        env:
          RUSTUP_PERMIT_COPY_RENAME:
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: clippy
          cache: false

      - name: Run 'cargo check'
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run 'cargo clippy'
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Check formatting
        run: |
          cargo fmt --all -- --check

      - name: Check typos
        uses: crate-ci/typos@master

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: "latest"

      - name: Build hydrating application
        run: |
          mkdir dist
          trunk build --features hydration

      - name: Perform site generation
        run: cargo run --features static --bin site-build

      - name: Install static file server
        run: |
          wget https://github.com/static-web-server/static-web-server/releases/download/v2.23.0/static-web-server-v2.23.0-x86_64-unknown-linux-musl.tar.gz -O target/static-web-server.tar.gz
          tar xfvz target/static-web-server.tar.gz -C target
          cp target/static-web-server-v2.23.0-x86_64-unknown-linux-musl/static-web-server $HOME/.cargo/bin/static-web-server

      - name: Run cypress tests (debug)
        run: yarn run ci:debug

      - name: Run cypress tests (release)
        run: yarn run ci:release
