#
# certificate.yaml
#
# Certificate for BlakeRain website
#

Description: CloudFormation template for blakerain.com certificate

Parameters:
  DomainName:
    Type: String
    Description: The domain name to use
    Default: blakerain.com

  HostedZoneId:
    Type: String
    Description: The hosted zone for the domain
    Default: Z2C0W1IB1QO9DO

Resources:
  BlakeRainCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Ref DomainName
        - !Sub www.${DomainName}
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub www.${DomainName}
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  BlakeRainCertificateArn:
    Description: The certificate ARN
    Value: !Ref BlakeRainCertificate
    Export:
      Name: !Sub ${AWS::StackName}-BlakeRainCertificateArn
