name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install node dependencies
        run: |
          npm i

      - name: Setup node
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build the site
        run: hugo --minify

      - name: Check typos
        uses: crate-ci/typos@master
