name: deploy

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install node dependencies
        run: |
          npm i

      - name: Setup node
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build the site
        run: hugo --minify

      - name: Connect to ZeroTier
        uses: zerotier/github-action@v1.0.1
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          access_token: ${{ secrets.ZEROTIER_ACCESS_TOKEN }}

      - name: Deploy the site
        run: |
          echo "${{ secrets.SSH_DEPLOYMENT_KEY }}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chrlvzi --delete \
            -e 'ssh -i ./deploy_key -p 22 -o StrictHostKeyChecking=no' \
            public/ \
            blakerain-com@${{ secrets.ZEROTIER_AMBER_IP }}:~/www/
          rm ./deploy_key
