name: deploy

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install node dependencies
        run: |
          npm i

      - name: Setup node
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: latest
          extended: true

      - name: Build the site
        run: hugo --minify

      - name: Setup WireGuard
        run: |
          sudo apt-get install -y wireguard-tools
          ifname="wg$(openssl rand -hex 4)"
          port="$(shuf --input-range=51000-51999 --head-count=1)"
          sudo ip link add "$ifname" type wireguard
          sudo ip addr add "${{ secrets.WIREGUARD_IP }}" dev "$ifname"
          sudo wg set "$ifname" \
            listen-port "$port" \
            private-key <(echo "${{ secrets.WIREGUARD_PRIVATE_KEY }}") \
            preshared-key <(echo "${{ secrets.WIREGUARD_PRESHARED_KEY }}") \
            peer "${{ secrets.WIREGUARD_AMBER_PUBLIC_KEY }}" \
            endpoint "${{ secrets.WIREGUARD_AMBER_ENDPOINT }}" \
            allowed-ips "${{ secrets.WIREGUARD_ALLOWED_IPS }}"
          sudo ip link set "$ifname" up
          sudo ip route replace "${{ secrets.WIREGUARD_ALLOWED_IPS }}" dev "$ifname"

      - name: Deploy the site
        run: |
          echo "${{ secrets.SSH_DEPLOYMENT_KEY }}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chrlvzi --delete \
            -e 'ssh -i ./deploy_key -p 22 -o StrictHostKeyChecking=no' \
            public/ \
            blakerain-com@${{ secrets.WIREGUARD_AMBER_IP }}:~/www/
          rm ./deploy_key
